import { describe,expect,it } from 'vitest';import { readFileSync } from 'node:fs';import { buildNewRecordPlan,readiness,validateDecisions,validateFulfillment } from '../scripts/data/lib/c4.2b-field-decisions';import { composeB4Lifecycle,validateB4 } from '../scripts/data/lib/c4.2b4-final-fields';import { validateDataset } from '../scripts/validation';
const text=(p:string)=>readFileSync(p,'utf8'),json=(p:string)=>JSON.parse(text(p)),clone=<T>(x:T):T=>JSON.parse(JSON.stringify(x));const p={b2f:'data/reviews/18.1/c4.2b2-field-evidence.json',b2:'data/reviews/18.1/c4.2b-field-decisions.json',b3f:'data/reviews/18.1/c4.2b3-required-field-evidence.json',b3:'data/reviews/18.1/c4.2b3-required-field-decisions.json',b4f:'data/reviews/18.1/c4.2b4-final-field-evidence.json',b4:'data/reviews/18.1/c4.2b4-final-field-decisions.json',manifest:'data/source_manifest_18.1.json',raw:'data/raw/18.1/20260903/opgg-zh-cn.html',headers:'data/raw/18.1/20260903/opgg-zh-cn.headers',parsed:'data/raw/18.1/20260903/opgg-final-blockers.json'};const [b2f,b2,b3f,b3,b4f,b4]=[p.b2f,p.b2,p.b3f,p.b3,p.b4f,p.b4].map(json),production=json('data/normalized/wisps_18.1.json'),inputs={b2FrozenText:text(p.b2f),b2OverlayText:text(p.b2),b3FrozenText:text(p.b3f),b3OverlayText:text(p.b3),canonicalManifestText:text(p.manifest),rawFiles:{[p.raw]:text(p.raw),[p.headers]:text(p.headers),[p.parsed]:text(p.parsed)}};
describe('C4.2B4 final supplemental governance',()=>{
 it('validates five manual amendments and detects raw, historical, bundle, and decision drift',()=>{expect(validateB4(b4f,b4,inputs)).toEqual([]);for(const [f,d,i] of [[{...clone(b4f),bundleSha256:'bad'},b4,inputs],[b4f,{...clone(b4),decisionSha256:'bad'},inputs],[b4f,b4,{...inputs,b3OverlayText:'{}'}],[b4f,b4,{...inputs,rawFiles:{[p.raw]:'changed'}}]] as any[])expect(validateB4(f,d,i).length).toBeGreaterThan(0)});
 it.each([['tier','B'],['confidence','official'],['useFor',['category','category_cross_check','invented']],['valueLocale','en_us']])('rejects fresh evidence %s drift',(field,value)=>{const frozen=clone(b4f),e=frozen.reviewTargets.find((x:any)=>x.field==='category').evidence[0];e[field]=value;expect(validateB4(frozen,b4,inputs)).not.toEqual([])});
 it.each([['TigersVisit','category','Support'],['TigersVisit','condition','changed'],['Snacktime','cost',99]])('rejects parsed %s.%s drift',(_key,field,value)=>{const parsed=json(p.parsed),row=parsed.records.find((x:any)=>x.key===_key);row[field]=value;const changed={...inputs,rawFiles:{...inputs.rawFiles,[p.parsed]:JSON.stringify(parsed)}};expect(validateB4(b4f,b4,changed)).not.toEqual([])});
 it('composes B2+B3+B4 through the existing lifecycle and leaves honest blockers',()=>{const effective=composeB4Lifecycle(b2f,b2,b3f,b3,b4f,b4);expect(validateDecisions(effective.frozen,effective.overlay,production)).toEqual([]);const rows=readiness(effective.frozen,effective.overlay);expect(rows.find((r:any)=>r.communityDragonId==='DA_TigersVisit18_Wisp').status).toBe('READY');expect(rows.filter((r:any)=>r.status==='READY')).toHaveLength(5);expect(rows.reduce((n:number,r:any)=>n+r.requiredBlockers.length,0)).toBe(3);const tiger=buildNewRecordPlan(effective.frozen,effective.overlay,'DA_TigersVisit18_Wisp')!;expect(validateDataset({patch:'18.1',records:[tiger]})).toEqual([]);expect(validateFulfillment(effective.frozen,effective.overlay,{records:[...production.records,tiger]})).toEqual([])});
 it('keeps Bear and Snacktime blocked when their B4 amendments remain unresolved',()=>{const effective=composeB4Lifecycle(b2f,b2,b3f,b3,b4f,b4),rows=readiness(effective.frozen,effective.overlay);for(const id of ['DA_BearsVisit18','DA_Snacktime18']){expect(rows.find((r:any)=>r.communityDragonId===id).status).toBe('BLOCKED');expect(buildNewRecordPlan(effective.frozen,effective.overlay,id)).toBeUndefined()}});
});
