import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { buildNewRecordPlan, readiness, validateDecisions, validateFulfillment } from '../scripts/data/lib/c4.2b-field-decisions';
import { composeEffectiveFieldDecisions, validateB3 } from '../scripts/data/lib/c4.2b3-required-fields';
import { validateDataset } from '../scripts/validation';
const text=(p:string)=>readFileSync(p,'utf8'),clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v));
const frozen=JSON.parse(text('data/reviews/18.1/c4.2b3-required-field-evidence.json')),decisions=JSON.parse(text('data/reviews/18.1/c4.2b3-required-field-decisions.json')),b2FrozenText=text('data/reviews/18.1/c4.2b2-field-evidence.json'),b2Text=text('data/reviews/18.1/c4.2b-field-decisions.json'),b2Frozen=JSON.parse(b2FrozenText),b2=JSON.parse(b2Text),production=b2Frozen.productionBaseline;
describe('C4.2B3 supplemental governance',()=>{
 it('validates six amendments and detects frozen evidence tampering',()=>{expect(validateB3(frozen,decisions,b2FrozenText,b2Text)).toEqual([]);const changed=clone(frozen),life=changed.reviewTargets.find((t:any)=>t.communityDragonId==='DA_PottedLifebloom18');life.evidence[0].rawValue=999;expect(validateB3(changed,decisions,b2FrozenText,b2Text)).toContain('B3 frozen bundle SHA mismatch')});
 it('rejects B2-origin drift, orphan, duplicate, unsupported, and invalid-shaped approvals',()=>{const drift=clone(frozen);drift.reviewTargets.find((t:any)=>t.evidence.length).evidence[0].sourceId='drift';expect(validateB3(drift,decisions,b2FrozenText,b2Text).join('\n')).toContain('drifted from B2 evidence');for(const mutate of [(d:any)=>d.amendments[0].communityDragonId='orphan',(d:any)=>d.amendments.push(clone(d.amendments[0])),(d:any)=>{d.amendments[0].action='approve_explicit_value';d.amendments[0].approvedValue='not-a-category'},(d:any)=>{d.amendments.find((x:any)=>x.action==='approve_explicit_value').approvedValue=99}]){const copy=clone(decisions);mutate(copy);expect(validateB3(frozen,copy,b2FrozenText,b2Text).length).toBeGreaterThan(0)}});
 it('reuses the B2 lifecycle for composed readiness and fulfillment',()=>{const effective=composeEffectiveFieldDecisions(b2,decisions,frozen);expect(validateDecisions(b2Frozen,effective,production)).toEqual([]);expect(effective.decisions.filter((d:any)=>!decisions.amendments.some((a:any)=>a.b2ReviewId===d.reviewId))).toEqual(b2.decisions.filter((d:any)=>!decisions.amendments.some((a:any)=>a.b2ReviewId===d.reviewId)));expect(readiness(b2Frozen,b2).find((r:any)=>r.communityDragonId==='DA_PottedLifebloom18').status).toBe('BLOCKED');const rows=readiness(b2Frozen,effective);expect(rows.find((r:any)=>r.communityDragonId==='DA_PottedLifebloom18').status).toBe('READY');for(const id of ['DA_Snacktime18','DA_BearsVisit18','DA_TigersVisit18_Wisp'])expect(rows.find((r:any)=>r.communityDragonId===id).status).toBe('BLOCKED');expect(rows.filter((r:any)=>r.status==='READY')).toHaveLength(4);expect(rows.reduce((n:number,r:any)=>n+r.requiredBlockers.length,0)).toBe(5);const record=buildNewRecordPlan(b2Frozen,effective,'DA_PottedLifebloom18')!;expect(record).toBeTruthy();expect(validateDataset({patch:'18.1',records:[record]})).toEqual([]);expect(validateFulfillment(b2Frozen,effective,{records:[...production.records,record]})).toEqual([])});
});
