import{describe,expect,it}from'vitest';import{canonicalText,compareEvidence,expandRequirementPropositions,resolveClientVariables,validateEvidenceMetadata}from'../scripts/data/lib/field-review';import{buildFieldReviewPacket,createRequirementReviewItems,renderMarkdown}from'../scripts/data/field-review-packet-18.1';import{validatePacket}from'../scripts/validate-c4.2b-field-review-packet';
describe('C4.2B1 evidence governance',()=>{
 it('does not make different effects agree through identity',()=>expect(compareEvidence([{normalizedInterpretation:canonicalText('gain a bear')},{normalizedInterpretation:canonicalText('gain a tiger')}]).reviewClass).toBe('human_conflict'));
 it('resolves generic client placeholders',()=>expect(resolveClientVariables('under @ExecuteThreshold*100@%',{ExecuteThreshold:.15})).toEqual([{variable:'ExecuteThreshold',rawValue:.15,displayValue:15,unit:'percent'}]));
 it('keeps distinct Chinese requirements distinct',()=>{const x=expandRequirementPropositions(['上一场战斗中上阵了5个1费弈子','拥有5个1费弈子']);expect(new Set(x.map(v=>v.key)).size).toBe(2)});
 it('keeps nonnumeric Chinese requirements distinct',()=>expect(new Set(expandRequirementPropositions(['已激活永恒之森','尚未选择灵龟']).map(v=>v.key)).size).toBe(2));
 it('rejects manifest confidence drift and incompatible useFor',()=>{const m={sources:[{sourceId:'s',tier:'C',confidence:'real',locale:'en',useFor:['requirements_cross_check']}]};expect(validateEvidenceMetadata({sourceId:'s',tier:'C',confidence:'fake',sourceLocaleCoverage:'en',valueLocale:'en'},m,'requirements')).toContain('s confidence drift');expect(validateEvidenceMetadata({sourceId:'s',tier:'C',confidence:'real',sourceLocaleCoverage:'en',valueLocale:'en'},m,'cost')).toContain('s useFor incompatible with cost')});
 it('rejects multi as localized value locale',()=>{const m={sources:[{sourceId:'s',tier:'B',confidence:'x',locale:'multi',useFor:['effect_cross_check']}]};expect(validateEvidenceMetadata({sourceId:'s',tier:'B',confidence:'x',sourceLocaleCoverage:'multi',valueLocale:'multi'},m,'effects.normal')).toContain('s imprecise localized value locale')});
 it('keeps Snacktime numeric proposition separate from the full effect',async()=>{const{packet}=await buildFieldReviewPacket();const i=packet.reviewItems.find((x:any)=>x.identity.communityDragonId==='DA_Snacktime18'&&x.field==='effects.normal')!;expect(i.propositionKey).toBe('client-variable-executethreshold');expect(i.candidateValues).toEqual(expect.arrayContaining([15,10,16]));expect(i.evidence.every((e:any)=>e.rawValue===undefined||typeof e.rawValue==='string')).toBe(true);expect(i.proposedProductionValue).toBeUndefined();expect(i.productionCandidateValues.every((v:any)=>typeof v==='string')).toBe(true);});
 it('contains full Lifebloom 2/2/3 cost evidence',async()=>{const{packet}=await buildFieldReviewPacket();const i=packet.reviewItems.find((x:any)=>x.identity.communityDragonId==='DA_PottedLifebloom18'&&x.field==='cost')!;expect(i.evidence.map((e:any)=>e.rawValue)).toEqual(expect.arrayContaining([2,2,3]));});
 it('includes LoLCHESS Bear evidence',async()=>{const{packet}=await buildFieldReviewPacket();const own=packet.reviewItems.filter((x:any)=>x.identity.communityDragonId==='DA_BearsVisit18');expect(own.flatMap((x:any)=>x.evidence).some((e:any)=>e.sourceId==='lolchess_set18_wisps_browser_import'&&e.rawValue!==undefined)).toBe(true)});
 it('existing requirement and variants contain record evidence',async()=>{const{packet}=await buildFieldReviewPacket();for(const f of ['requirements','effects.blossom','effects.prismatic'])for(const i of packet.reviewItems.filter((x:any)=>x.identity.productionId&&x.field===f))expect(i.evidence.some((e:any)=>e.sourceId!=='c4.1-release-readiness')).toBe(true)});
 it('integrates two requirements as two generated propositions',()=>{const rows=createRequirementReviewItems({communityDragonId:'synthetic'},[{sourceId:'s',valueLocale:'zh_cn',rawValue:['上一场战斗中上阵了5个1费弈子','尚未选择灵龟'],normalizedInterpretation:[],comparisonValue:[],proposedProductionValue:[]}]);expect(rows).toHaveLength(2);expect(new Set(rows.map((r:any)=>r.propositionKey)).size).toBe(2)});
 it('supports structured agreement only with a production-shaped target',()=>expect(compareEvidence([{normalizedInterpretation:{type:'gold',operator:'>=',value:30},proposedProductionValue:[{type:'gold',operator:'>=',value:30}]},{normalizedInterpretation:{type:'gold',operator:'>=',value:30},proposedProductionValue:[{type:'gold',operator:'>=',value:30}]}]).reviewClass).toBe('decision_ready'));
 it('never emits a non-string decision-ready normal effect proposal',async()=>{const{packet}=await buildFieldReviewPacket();for(const i of packet.reviewItems.filter((x:any)=>x.field==='effects.normal'&&x.reviewClass==='decision_ready'))expect(typeof i.proposedProductionValue).toBe('string')});
 it('reconciles validator summary and deterministic Markdown',async()=>{const a=await buildFieldReviewPacket(),b=await buildFieldReviewPacket();expect(a.json).toBe(b.json);expect(a.markdown).toBe(renderMarkdown(a.packet));const manifest=await import('../data/source_manifest_18.1.json');expect(validatePacket(a.packet,manifest.default)).toEqual([])});
});
