import{describe,expect,it}from'vitest';import{readFileSync}from'node:fs';import{readiness,validateDecisions,validateFulfillment}from'../scripts/data/lib/c4.2b-field-decisions';
const frozen=JSON.parse(readFileSync('data/reviews/18.1/c4.2b2-field-evidence.json','utf8')),overlay=JSON.parse(readFileSync('data/reviews/18.1/c4.2b-field-decisions.json','utf8')),production=JSON.parse(readFileSync('data/normalized/wisps_18.1.json','utf8'));
const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v));
describe('C4.2B2 decision governance',()=>{
 it('binds the exact frozen bundle and validates independently of current B1',()=>{expect(overlay.evidenceBinding.frozenEvidenceSha256).toBe(frozen.bundleSha256);expect(validateDecisions(frozen,overlay,production)).toEqual([])});
 it('detects missing, duplicate, and orphan dispositions',()=>{for(const mutate of [(d:any)=>d.decisions.pop(),(d:any)=>d.decisions.push(clone(d.decisions[0])),(d:any)=>d.decisions[0].reviewId='orphan']){const d=clone(overlay);mutate(d);expect(validateDecisions(frozen,d).length).toBeGreaterThan(0)}});
 it('enforces action admissibility',()=>{const cases:Array<(d:any)=>void>=[d=>{d.action='approve_proposal';d.approvedValue='invented';d.applyPolicy='apply'},d=>{d.action='approve_explicit_value';d.approvedValue=987654;d.applyPolicy='apply'},d=>{d.action='retain_current'},d=>{d.action='accepted_unknown';d.approvedValue=false},d=>{d.action='confirmed_absent'}];for(const mutate of cases){const d=clone(overlay),x=d.decisions.find((v:any)=>!v.identity.productionId&&v.action==='unresolved')!;mutate(x);expect(validateDecisions(frozen,d).length).toBeGreaterThan(0)}});
 it('allows optional unknown without readiness but blocks unresolved required fields',()=>{const rows=readiness(frozen,overlay);expect(rows.find((r:any)=>r.communityDragonId==='DA_BearsVisit18').requiredBlockers).toContain('category');expect(rows.every((r:any)=>r.optionalUnknown.includes('effects.prismatic'))).toBe(true)});
 it('keeps Bear, Tiger, and Bear Upgrade identities distinct',()=>{const ids=frozen.missingIdentities.map((x:any)=>x.communityDragonId);expect(ids).toContain('DA_TigersVisit18_Wisp');expect(ids).toContain('DA_BearsVisit18');expect(ids).not.toContain('DA_BearsVisit18_Upgrade')});
 it('guards future apply lifecycle',()=>{const base={records:[{id:'one',riotId:'R1',cost:1,effects:{normal:'old'}}]},f:any={missingIdentities:[{communityDragonId:'R2'}],reviewItems:[{reviewId:'a',field:'cost',proposedProductionValue:2,identity:{productionId:'one'}},{reviewId:'u',field:'effects.normal',identity:{productionId:'one'}},{reviewId:'n',field:'riotId',proposedProductionValue:'R2',identity:{communityDragonId:'R2'}}],productionBaseline:base},d:any={decisions:[{reviewId:'a',action:'approve_proposal',approvedValue:2,identity:{productionId:'one'},field:'cost'},{reviewId:'u',action:'unresolved',identity:{productionId:'one'},field:'effects.normal'},{reviewId:'n',action:'approve_proposal',approvedValue:'R2',identity:{communityDragonId:'R2'},field:'riotId'}]};expect(validateFulfillment(f,d,{records:[{...base.records[0],cost:2},{id:'two',riotId:'R2'}]})).toEqual([]);expect(validateFulfillment(f,d,{records:[{...base.records[0],cost:9}]}).join()).toContain('wrong approved');expect(validateFulfillment(f,d,{records:[{...base.records[0],nameEn:'mutation'}]}).join()).toContain('unapproved');expect(validateFulfillment(f,d,{records:[{...base.records[0],effects:{normal:'changed'}}]}).join()).toContain('unapproved');expect(validateFulfillment(f,d,{records:[base.records[0],{id:'two',riotId:'WRONG'}]}).join()).toContain('unapproved new identity');expect(validateFulfillment(f,d,{records:[base.records[0],{id:'two',riotId:'R2'},{id:'three',riotId:'R2'}]}).join()).toContain('duplicate new identity')});
});
