import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { describe, expect, it } from 'vitest';
import { validateIdentityDecisions, type C42A4EvidenceBundle, type DecisionValidationInput, type IdentityDecisionFile } from '../scripts/data/lib/identity-decisions';
const read = (path: string) => readFile(path, 'utf8'); const sha = (text: string) => createHash('sha256').update(text).digest('hex'); const clone = <T>(value: T): T => structuredClone(value);
async function fixture(): Promise<DecisionValidationInput> {
  const [decisionText, evidenceText, productionText, mappingText, readinessText] = await Promise.all([read('data/reviews/18.1/c4.2a-identity-decisions.json'), read('data/reviews/18.1/c4.2a4-identity-evidence.json'), read('data/normalized/wisps_18.1.json'), read('data/overrides/18.1/reviewed-identity-mappings.json'), read('reports/release-readiness-18.1.json')]);
  return { decisions: JSON.parse(decisionText) as IdentityDecisionFile, frozenEvidence: JSON.parse(evidenceText) as C42A4EvidenceBundle, frozenEvidenceSha256: sha(evidenceText), production: JSON.parse(productionText) as DecisionValidationInput['production'], mappings: JSON.parse(mappingText) as DecisionValidationInput['mappings'], currentState: { productionSha256: sha(productionText), reviewedMappingsSha256: sha(mappingText), releaseReadinessSha256: sha(readinessText), recommendedProductionReady: (JSON.parse(readinessText) as { recommendedProductionReady: boolean }).recommendedProductionReady } };
}
const mutate = async (fn: (input: DecisionValidationInput) => void) => { const input = clone(await fixture()); fn(input); return validateIdentityDecisions(input); };
const applyMissing = (input: DecisionValidationInput) => { for (const row of input.decisions.decisions.filter((item) => item.action === 'missing_base_identity')) { const productionId = `applied_${row.communityDragonId}`; input.production.records.push({ id: productionId, riotId: row.communityDragonId }); input.mappings.records.push({ communityDragonId: row.communityDragonId, productionId }); } };

describe('C4.2A4 frozen historical evidence and apply lifecycle', () => {
  it('validates current pre-apply decisions as 8 pending from the frozen bundle', async () => { const result = validateIdentityDecisions(await fixture()); expect(result.errors).toEqual([]); expect(result.totals).toEqual({ decisions: 8, sameIdentity: 1, missingBaseIdentity: 7, pending: 8, fulfilled: 0 }); });
  it('keeps identity decisions valid when only current release audit changes', async () => { const input = await fixture(); input.currentState.releaseReadinessSha256 = 'f'.repeat(64); expect(validateIdentityDecisions(input).errors).toEqual([]); });
  it('keeps identity decisions valid when only current readiness recommendation changes', async () => { const input = await fixture(); input.currentState.recommendedProductionReady = !input.currentState.recommendedProductionReady; expect(validateIdentityDecisions(input).errors).toEqual([]); });
  it('rejects an unexpected production change before apply', async () => { const input = await fixture(); input.production.records.push({ id: 'unrelated-pre-apply-change' }); input.currentState.productionSha256 = 'e'.repeat(64); expect(validateIdentityDecisions(input).errors).toContain('Current pre-apply identity state does not match the recorded decision baseline.'); });
  it('rejects an unexpected reviewed-mapping change before apply', async () => { const input = await fixture(); input.currentState.reviewedMappingsSha256 = 'd'.repeat(64); expect(validateIdentityDecisions(input).errors).toContain('Current pre-apply identity state does not match the recorded decision baseline.'); });
  it('accepts correct future missing-base fulfillment', async () => { const input = await fixture(); applyMissing(input); const result = validateIdentityDecisions(input); expect(result.errors).toEqual([]); expect(result.totals).toMatchObject({ pending: 1, fulfilled: 7 }); });
  it('does not consume regenerated current A2/A3 for historical admissibility', async () => { const input = await fixture(); const regeneratedCurrentAudit = { a2Sha256: 'changed-after-apply', rows: input.frozenEvidence.identities.map((row) => ({ communityDragonId: row.communityDragonId, classification: 'existing_base_identity_already_in_production' })) }; applyMissing(input); regeneratedCurrentAudit.rows.forEach((row) => expect(row.classification).toBe('existing_base_identity_already_in_production')); const result = validateIdentityDecisions(input); expect(result.errors).toEqual([]); expect(result.totals).toMatchObject({ pending: 1, fulfilled: 7 }); });
  it('keeps correct post-regeneration apply valid even when current A2/A3 hashes differ', async () => { const input = await fixture(); applyMissing(input); const simulatedCurrentReports = { a2: { proposals: [] }, a3: { sha256: 'different', freshOnlyOrChangedRows: [] } }; expect(simulatedCurrentReports.a3.sha256).not.toBe(input.frozenEvidence.sourceArtifactHashes.a3); expect(validateIdentityDecisions(input).errors).toEqual([]); });
  it('accepts the approved Clone mapping and marks it fulfilled', async () => { const input = await fixture(); input.mappings.records.push({ communityDragonId: 'DA_CloneCompanion18', productionId: 'snapshot_139_6fda4e76a4da' }); const result = validateIdentityDecisions(input); expect(result.errors).toEqual([]); expect(result.fulfillment[0]?.status).toBe('fulfilled'); });
  it('rejects wrong, duplicate, and wrong-client apply mappings', async () => { expect((await mutate((x) => x.mappings.records.push({ communityDragonId: 'DA_CloneCompanion18', productionId: 'da_ironwood18' }))).errors).toContainEqual(expect.stringContaining('disagrees with approved productionId')); expect((await mutate((x) => { const id = 'bear'; x.production.records.push({ id, riotId: 'DA_BearsVisit18' }); x.mappings.records.push({ communityDragonId: 'DA_BearsVisit18', productionId: id }, { communityDragonId: 'DA_BearsVisit18', productionId: id }); })).errors).toContainEqual(expect.stringContaining('duplicate apply targets')); expect((await mutate((x) => { x.production.records.push({ id: 'upgrade', riotId: 'DA_BearsVisit18_Upgrade' }); x.mappings.records.push({ communityDragonId: 'DA_BearsVisit18', productionId: 'upgrade' }); })).errors).toContainEqual(expect.stringContaining('wrong client identity')); });
  it('rejects stale frozen-bundle binding', async () => expect((await mutate((x) => { x.frozenEvidenceSha256 = '0'.repeat(64); })).errors).toContain('identity decisions stale against frozen C4.2A4 evidence'));
  it('rejects unsupported historical same or missing actions', async () => { expect((await mutate((x) => { const evidence = x.frozenEvidence.identities[0]!.historicalAdmissibility; if (evidence.kind === 'same_identity') evidence.policyCompliantTargets = []; })).errors).toContainEqual(expect.stringContaining('same_identity action is not admissible')); expect((await mutate((x) => { const evidence = x.frozenEvidence.identities[1]!.historicalAdmissibility; if (evidence.kind === 'missing_base_identity') evidence.a3Classification = 'existing_base_identity_already_in_production'; })).errors).toContainEqual(expect.stringContaining('missing_base_identity action is not admissible')); });
  it('rejects unresolved evidence refs and canonical-name drift', async () => { expect((await mutate((x) => x.decisions.decisions[0]!.evidenceRefs.push('A3:freshIndex-999'))).errors).toContainEqual(expect.stringContaining('evidenceRef')); expect((await mutate((x) => { x.decisions.decisions[1]!.canonicalNameZh = '错误'; })).errors).toContainEqual(expect.stringContaining('canonical identity drift')); });
  it('rejects Tiger upgrade misuse without relying on decisionId', async () => expect((await mutate((x) => { x.decisions.decisions[6]!.communityDragonId = 'DA_BearsVisit18_Upgrade'; })).errors).toContainEqual(expect.stringContaining('frozen identity evidence')));
  it('rejects duplicate client decisions and field leakage', async () => { expect((await mutate((x) => { x.decisions.decisions[2]!.communityDragonId = 'DA_BearsVisit18'; })).errors).toContain('Duplicate communityDragonId.'); expect((await mutate((x) => { Object.assign(x.decisions.decisions[5]!, { fieldResolutionStatus: 'approved' }); })).errors).toContainEqual(expect.stringContaining('field resolution leaked')); });
  it('generates a deterministic report without rewriting decisions or frozen evidence', async () => { const decisionBefore = sha(await read('data/reviews/18.1/c4.2a-identity-decisions.json')); const evidenceBefore = sha(await read('data/reviews/18.1/c4.2a4-identity-evidence.json')); execFileSync('npm', ['run', 'data:c4.2a-identity-decision-report:18.1'], { stdio: 'pipe' }); const reportOnce = sha(await read('reports/c4.2a4-identity-decisions-18.1.md')); execFileSync('npm', ['run', 'data:c4.2a-identity-decision-report:18.1'], { stdio: 'pipe' }); expect(sha(await read('reports/c4.2a4-identity-decisions-18.1.md'))).toBe(reportOnce); expect(sha(await read('data/reviews/18.1/c4.2a-identity-decisions.json'))).toBe(decisionBefore); expect(sha(await read('data/reviews/18.1/c4.2a4-identity-evidence.json'))).toBe(evidenceBefore); });
});
