import { describe, expect, it } from 'vitest';
import { readFile } from 'node:fs/promises';
import { buildPriorityIdentityProposals, deriveIdentityProposal, type ProductionSearch } from '../scripts/data/priority-identity-proposals-18.1';
const evidence = (productionId?: string) => ({ sourceId: 'synthetic', snapshotPath: 'synthetic.json', selector: '$', evidenceClass: 'identity_confirming' as const, note: 'synthetic', ...(productionId ? { productionId } : {}) });
const search = (overrides: Partial<ProductionSearch> = {}): ProductionSearch => ({ productionRecordCount: 2, queryNames: [], exactIdOrKeyMatches: [], exactEnglishNameMatches: [], exactChineseNameMatches: [], normalizedNameMatches: [], reviewedMappingMatches: [], sourceRowContinuityMatches: [], policyCompliantTargets: [], unresolvedReviewRelevantCandidates: [], topFuzzyCandidates: [], exclusionEvidence: [], exhaustiveConclusion: '', ...overrides });
describe('evidence-derived identity proposal rules', () => {
  it('produces same_identity for any cluster-like input with exactly one compliant target', () => expect(deriveIdentityProposal({ corpusConfirmed: true, search: search({ policyCompliantTargets: ['not-c4i-001-target'] }), corpusEvidence: [evidence()] })).toMatchObject({ proposedAction: 'same_identity', proposedProductionId: 'not-c4i-001-target' }));
  it('does not produce strong distinct when a plausible target remains unresolved', () => expect(deriveIdentityProposal({ corpusConfirmed: true, search: search({ unresolvedReviewRelevantCandidates: [{ productionId: 'plausible' }] }), corpusEvidence: [evidence(), evidence()] })).toMatchObject({ proposedAction: 'insufficient_evidence', missingProductionHypothesis: 'moderate' }));
  it('requires confirmed corpus, no plausible target, and exclusion evidence for a strong missing hypothesis', () => expect(deriveIdentityProposal({ corpusConfirmed: true, search: search({ exclusionEvidence: [evidence()] }), corpusEvidence: [evidence(), evidence()] })).toMatchObject({ proposedAction: 'insufficient_evidence', productionMissingCandidate: true, missingProductionHypothesis: 'strong' }));
  it('loses C4I-001 same_identity when its continuity target evidence is removed', async () => { const report = JSON.parse((await buildPriorityIdentityProposals()).json); const clone = report.proposals.find((proposal: any) => proposal.clusterId === 'C4I-001'); const withoutContinuity = deriveIdentityProposal({ corpusConfirmed: true, search: search({ policyCompliantTargets: clone.productionSearch.policyCompliantTargets.filter((target: string) => target !== clone.proposedProductionId) }), corpusEvidence: clone.confirmingEvidence }); expect(withoutContinuity.proposedAction).not.toBe('same_identity'); });
  it('is independent of packet cluster order', async () => { const packet = JSON.parse(await readFile('reports/c4.2a-identity-review-packet-18.1.json', 'utf8')); const normal = await buildPriorityIdentityProposals(packet); const shuffled = await buildPriorityIdentityProposals({ ...packet, clusters: [...packet.clusters].reverse() }); expect(shuffled).toEqual(normal); });
  it('keeps field conflicts and punctuation normalization supporting-only', async () => { const report = JSON.parse((await buildPriorityIdentityProposals()).json); const snack = report.proposals.find((proposal: any) => proposal.sourceIdentity === 'Snacktime'); const turtle = report.proposals.find((proposal: any) => proposal.sourceIdentity === 'TurtlesVisit'); expect(snack.fieldReviewFollowUps.some((item: any) => item.field === 'cost')).toBe(true); expect(snack.confirmingEvidence.some((item: any) => item.evidenceClass === 'field_conflict')).toBe(false); expect(turtle.supportingEvidence.some((item: any) => item.note.includes("Turtle's Visit"))).toBe(true); });
  it('is byte deterministic', async () => expect(await buildPriorityIdentityProposals()).toEqual(await buildPriorityIdentityProposals()));
});
